class_name ArticyDebug extends ArticyData


static func log_articy_info(ar: ArticyResource):
	if ArticyNylonConverter.verbose_log and ar:
		print("Begin parsing Articy node.")
		
		if ar.type:
			print("Type: " + ar.type)
		if ar.id:
			print("Articy ID: " + ar.id)
		
		if ar.output_target:
			print("Connections found:")
			print(ar.output_target)
		else:
			print("No output connections found for " + ar.id)
		print()


static func log_nylon_info(ar: ArticyResource, n: NylonNode):
	if ArticyNylonConverter.verbose_log and ar:
		print(ar.id + " has added a new NylonNode to the scene tree.")
		print("Class: " + n.get_script().get_global_name())
		print("Parent: " + String(n.get_parent().name))
		print("Name: " + String(n.name))
		print("Nylon ID: " + n.node_id)
		print(" ")


static func log_hub_branches(ar: ArticyResource):
	if ar is ArticyHub:
		var branches: Array[ArticyResource] = convert_output_ids(ar.hub_targets.keys())
		if ArticyNylonConverter.verbose_log:
			if branches:
				print("Branches: ")
				for branch in branches:
					print("Articy ID: " + branch.id)
				print()
			else:
				print("WARNING: Hub with ID " + ar.id + " connects to no branches.")


static func log_aatt_properties(aatt: ArticyAddToTree):
	if aatt:
		print("Logging properties for aatt generated by: " + str(aatt.ar.id))
		print("Node: " + str(aatt.node))


static func log_ar_properties(ar: ArticyResource):
	if ar:
		print("Logging properties for " + str(ar.id))
		print("Type: " + str(ar.type))
		print("Technical Name: " + str(ar.technical_name))
		print("display_name: " + str(ar.display_name))
		print("text: " + ar.text)
		print("targeted_pin: " + str(ar.targeted_pin))
		print("assigned_sequence: " + str(ar.assigned_sequence))
		print("Sources: " + str(ar.sources))
		print("active_IO: " + str(ar.active_IO))
		print()
		if ar.main_input_target:
			print("~INPUT INFORMATION~")
			print("input_pins: " + str(ar.input_pins))
			print("main_input_pin_id: " + str(ar.main_input_pin.id))
			print("main_input_target_id: " + str(ar.main_input_target.id))
			print("main_input_target_pin_id: " + str(ar.main_input_target_pin.id))
			print()
		if ar.main_output_target:
			print("~OUTPUT INFORMATION~")
			print("output_pins: " + str(ar.output_pins))
			print("main_output_pin_id: " + str(ar.main_output_pin.id))
			print("main_output_target_id: " + str(ar.main_output_target.id))
			print("main_output_target_pin_id: " + str(ar.main_output_target_pin.id))
			print()
		print("Finished logging for " + str(ar.id))
		print()
		print()
